### PR TITLE
Fixed a compilation error in VS2015.

### PR DESCRIPTION
**Pull request by PazerOP**
Fixed ambiguous call to abs()

### CODE REVIEW

**Comment by Filip98** [comment]
is the code now fully compatible with VS2015 and backwards compatible with VS2013?

**Comment by joeangry** [comment]
It can't be until Valve releases updated libraries for things we don't have the source code for. It might compile fine but it won't link.

**Comment by Filip98** [comment]
damn, forgot about that.. well we're doomed until source 2, nothing new

**Comment by joeangry** [comment]
So exactly what is the point of your commits @PazerOP?

**Comment by LestaD** [comment]
@PazerOP Maybe squash all your commits in one?

**Comment by PazerOP** [comment]
What the fuck, why did all these commits get added to this pull request

**Pull request closed without merging**
